[package]
name = "match-rs"
version = "0.1.0"
authors = ["guotie <guotie.9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
